version: "3"
networks:
  tusker-network:
volumes:
  tusker-my-sql-data:
    driver: local
services:
  mysql:
    image: mysql:5.7.28
    container_name: tusker-mysql
    volumes:
      - tusker-my-sql-data:/var/lib/mysql
    networks:
      - tusker-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
